language: rust
cache: cargo
rust:
    - stable
    - beta
    - nightly
os:
    - windows
    - linux
    - osx

before_script:
    - |
      (travis_wait rustup component add rustfmt-preview || true) &&
      (travis_wait rustup component add clippy-preview || true)

script:
    - |
      export PATH="$PATH":~/.cargo/bin &&
      export RUST_BACKTRACE=1 &&
      export CARGO_INCREMENTAL=1 &&
      cargo build --all &&
      cargo test --all &&
      cargo build --all --all-features &&
      cargo test --all --all-features &&
      cargo doc --no-deps &&
      (test "$TRAVIS_RUST_VERSION" == nightly || cargo clippy --all --tests -- --deny clippy::all) &&
      (test "$TRAVIS_RUST_VERSION" == nightly || cargo fmt)
